<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Sekdin 2025 (vol 2) - Scrollable Buttons with Question Switch and Popup</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
</head>
<body class="bg-[#f8fafb] min-h-screen flex">
  <!-- Sidebar -->
  <?= view('components/sidebar', ['pengguna' => $pengguna]) ?>

  <main class="flex-1 p-6 max-w-full overflow-x-hidden relative">
    <div class="max-w-6xl mx-auto">
      <header class="mb-4 flex justify-between items-center">
        <h1 class="text-xl font-semibold text-gray-900" id="question-title"><?= $tryout['nama_tryout'] ?></h1>
        <a href="#" id="lihat-semua-btn" class="text-sm font-semibold text-[#3b9ad9] hover:underline cursor-pointer">Lihat Semua</a>
      </header>

      <!-- page dengan 110 tombol, scrollable horizontal -->
      <div id="question-buttons" class="flex gap-1 mb-4 overflow-x-auto scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100 whitespace-nowrap">
        <?php foreach ($questions as $question): ?>
          <button class="bg-white text-gray-900 w-8 h-8 rounded border border-gray-300 font-semibold inline-block px-1" onclick="selectQuestion(<?= $question['no_soal'] ?>)">
            <?= $question['no_soal'] ?>
          </button>
        <?php endforeach; ?>
      </div>

      <!-- Timer dan itungan question -->
      <section class="bg-white rounded-xl p-6 mb-6 flex justify-center items-center text-[#0f293f] font-semibold text-2xl relative">
        <div class="text-center w-full max-w-3xl">
          <span id="timer">1:39:56</span>
          <p class="text-sm font-normal mt-1">Soal Terjawab <span class="text-[#0f293f]" id="answered-count">0</span> / <span class="text-[#e74c3c]"><?= count($questions) ?></span></p>
        </div>
      </section>

      <!-- Question card -->
      <article id="question-card" class="bg-white rounded-xl p-6 text-gray-700 text-sm leading-relaxed">
        <header class="flex items-center gap-3 mb-3">
          <div id="question-number" class="bg-[#0f293f] text-white font-semibold rounded-md w-7 h-7 flex items-center justify-center">1</div>
          <h2 id="question-subject" class="font-semibold text-gray-900"></h2>
        </header>
        <p id="question-text" class="mb-6"></p>
        <hr class="border-gray-300 mb-6" />
        <ul id="options-list" class="flex flex-col gap-4 max-w-md">
          <!-- Options generated by JS -->
        </ul>
      </article>
    </div>

    <!-- Popup overlay nomor soal -->
    <div id="popup-overlay" class="fixed inset-0 bg-black bg-opacity-50 hidden items-center justify-center z-50">
      <div class="bg-white rounded-xl p-6 max-w-3xl w-full max-h-[80vh] overflow-y-auto">
        <header class="flex justify-between items-center mb-4">
          <h3 class="text-lg font-semibold text-gray-900">Pilih Nomor Soal</h3>
          <button id="popup-close-btn" class="text-gray-500 hover:text-gray-900 text-xl font-bold" aria-label="Close popup">&times;</button>
        </header>
        <div id="popup-buttons" class="grid grid-cols-10 gap-2 max-h-[60vh] overflow-y-auto">
          <!-- Buttons generated by JS -->
        </div>
      </div>
    </div>
  </main>

  <script>
    let questions = <?= json_encode($questions) ?>;
    let selectedQuestionIndex = 0;
    let userAnswers = {};

    // Render Question
    function renderQuestion(index) {
      const question = questions.find(q => q.no_soal === index);

      document.getElementById('question-number').innerText = question.no_soal;
      document.getElementById('question-subject').innerText = question.subject;
      document.getElementById('question-text').innerText = question.teks_soal;

      let optionsList = document.getElementById('options-list');
      optionsList.innerHTML = "";
      question.options.forEach((option, i) => {
        const li = document.createElement('li');
        const btn = document.createElement('button');
        btn.type = "button";
        btn.className = "flex items-center gap-4 w-full text-left";
        btn.onclick = () => selectAnswerAndNext(index, i);

        const circle = document.createElement('div');
        circle.className = "option-circle font-semibold rounded-md w-7 h-7 flex items-center justify-center";
        circle.textContent = ["A", "B", "C", "D", "E"][i];

        btn.appendChild(circle);
        const span = document.createElement('span');
        span.textContent = option;
        btn.appendChild(span);
        li.appendChild(btn);
        optionsList.appendChild(li);
      });
    }

    // Update Answered Count
    function updateAnsweredCount() {
      const count = Object.keys(userAnswers).length;
      document.getElementById('answered-count').textContent = count;
    }

    // Initialize
    renderQuestion(questions[0].no_soal);
  </script>
</body>
</html>
